CREATE TABLE `shopify_fulfillments` (
	`id` integer PRIMARY KEY NOT NULL,
	`shop_id` integer NOT NULL,
	`order_id` integer NOT NULL,
	`status` text,
	`tracking_company` text,
	`tracking_number` text,
	`tracking_numbers` text,
	`tracking_url` text,
	`tracking_urls` text,
	`receipt` text,
	`name` text,
	`created_at` text,
	`updated_at` text DEFAULT 'CURRENT_TIMESTAMP'
);
--> statement-breakpoint
CREATE TABLE `shopify_order_line_items` (
	`id` integer PRIMARY KEY NOT NULL,
	`order_id` integer NOT NULL,
	`shop_id` integer NOT NULL,
	`product_id` integer,
	`variant_id` integer,
	`title` text,
	`quantity` integer,
	`sku` text,
	`variant_title` text,
	`vendor` text,
	`fulfillment_service` text,
	`requires_shipping` integer,
	`taxable` integer,
	`gift_card` integer,
	`name` text,
	`variant_inventory_management` text,
	`properties` text,
	`product_exists` integer,
	`fulfillable_quantity` integer,
	`grams` integer,
	`price` real,
	`total_discount` real,
	`fulfillment_status` text,
	`price_set` text,
	`total_discount_set` text,
	`created_at` text,
	`updated_at` text DEFAULT 'CURRENT_TIMESTAMP'
);
--> statement-breakpoint
CREATE TABLE `shopify_product_variants` (
	`id` integer PRIMARY KEY NOT NULL,
	`product_id` integer NOT NULL,
	`shop_id` integer NOT NULL,
	`title` text,
	`price` real,
	`sku` text,
	`position` integer,
	`inventory_policy` text,
	`compare_at_price` real,
	`fulfillment_service` text,
	`inventory_management` text,
	`option1` text,
	`option2` text,
	`option3` text,
	`taxable` integer,
	`barcode` text,
	`grams` integer,
	`inventory_item_id` integer,
	`inventory_quantity` integer,
	`weight` real,
	`weight_unit` text,
	`created_at` text,
	`updated_at` text DEFAULT 'CURRENT_TIMESTAMP'
);
