import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const shops = sqliteTable('shopify_shops', {
  id: integer('id').primaryKey().notNull(),
  myshopify_domain: text('myshopify_domain').notNull().unique(),
  name: text('name'),
  email: text('email'),
  domain: text('domain'),
  currency: text('currency'),
  timezone: text('timezone'),
  iana_timezone: text('iana_timezone'),
  shop_owner: text('shop_owner'),
  plan_name: text('plan_name'),
  plan_display_name: text('plan_display_name'),
  latitude: real('latitude'),
  longitude: real('longitude'),
  address1: text('address1'),
  address2: text('address2'),
  city: text('city'),
  zip: text('zip'),
  province: text('province'),
  country: text('country'),
  country_code: text('country_code'),
  country_name: text('country_name'),
  phone: text('phone'),
  customer_email: text('customer_email'),
  money_format: text('money_format'),
  money_with_currency_format: text('money_with_currency_format'),
  weight_unit: text('weight_unit'),
  province_code: text('province_code'),
  setup_required: integer('setup_required', { mode: 'boolean' }),
  force_ssl: integer('force_ssl', { mode: 'boolean' }),
  primary_locale: text('primary_locale'),
  primary_location_id: integer('primary_location_id'),
  active_recurring_subscription_id: text('active_recurring_subscription_id'),
  plan_id: integer('plan_id'),
  used_trial_minutes: integer('used_trial_minutes').default(0),
  used_trial_minutes_updated_at: text('used_trial_minutes_updated_at'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  access_token: text('access_token').notNull(),
  scope: text('scope'),
  is_active: integer('is_active', { mode: 'boolean' }).default(true),
  installed_at: text('installed_at').default('CURRENT_TIMESTAMP'),
});

export const invoices = sqliteTable('invoices', {
  id: integer('id').primaryKey({ autoIncrement: true }).notNull(),
  shop_id: integer('shop_id').notNull(),
  order_id: integer('order_id'),
  invoice_number: text('invoice_number').notNull().unique(),
  status: text('status').default('draft'),
  pdf_url: text('pdf_url'),
  pdf_url_id: text('pdf_url_id'),
  sent_at: text('sent_at'),
  paid_at: text('paid_at'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const orders = sqliteTable('shopify_orders', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  customer_id: integer('customer_id'),
  email: text('email'),
  number: integer('number'),
  order_number: integer('order_number'),
  note: text('note'),
  token: text('token'),
  gateway: text('gateway'),
  test: integer('test', { mode: 'boolean' }),
  total_price: real('total_price'),
  subtotal_price: real('subtotal_price'),
  total_weight: integer('total_weight'),
  total_tax: real('total_tax'),
  taxes_included: integer('taxes_included', { mode: 'boolean' }),
  currency: text('currency'),
  financial_status: text('financial_status'),
  confirmed: integer('confirmed', { mode: 'boolean' }),
  total_discounts: real('total_discounts'),
  total_line_items_price: real('total_line_items_price'),
  name: text('name'),
  cancelled_at: text('cancelled_at'),
  cancel_reason: text('cancel_reason'),
  total_price_set: text('total_price_set'),
  subtotal_price_set: text('subtotal_price_set'),
  total_tax_set: text('total_tax_set'),
  total_discounts_set: text('total_discounts_set'),
  total_line_items_price_set: text('total_line_items_price_set'),
  fulfillment_status: text('fulfillment_status'),
  customer_locale: text('customer_locale'),
  processed_at: text('processed_at'),
  status_page_url: text('status_page_url'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  tags: text('tags'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const products = sqliteTable('shopify_products', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  title: text('title').notNull(),
  body_html: text('body_html'),
  vendor: text('vendor'),
  product_type: text('product_type'),
  handle: text('handle'),
  status: text('status'),
  published_at: text('published_at'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const customers = sqliteTable('shopify_customers', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  email: text('email'),
  first_name: text('first_name'),
  last_name: text('last_name'),
  orders_count: integer('orders_count'),
  state: text('state'),
  total_spent: text('total_spent'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const syncs = sqliteTable('shopify_syncs', {
  id: integer('id').primaryKey({ autoIncrement: true }).notNull(),
  shop_id: integer('shop_id'),
  domain: text('domain').notNull(),
  status: text('status'),
  models: text('models'), // JSON string
  error: text('error'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const productVariants = sqliteTable('shopify_product_variants', {
  id: integer('id').primaryKey().notNull(),
  product_id: integer('product_id').notNull(),
  shop_id: integer('shop_id').notNull(),
  title: text('title'),
  price: real('price'),
  sku: text('sku'),
  position: integer('position'),
  inventory_policy: text('inventory_policy'),
  compare_at_price: real('compare_at_price'),
  fulfillment_service: text('fulfillment_service'),
  inventory_management: text('inventory_management'),
  option1: text('option1'),
  option2: text('option2'),
  option3: text('option3'),
  taxable: integer('taxable', { mode: 'boolean' }),
  barcode: text('barcode'),
  grams: integer('grams'),
  inventory_item_id: integer('inventory_item_id'),
  inventory_quantity: integer('inventory_quantity'),
  weight: real('weight'),
  weight_unit: text('weight_unit'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const orderLineItems = sqliteTable('shopify_order_line_items', {
  id: integer('id').primaryKey().notNull(),
  order_id: integer('order_id').notNull(),
  shop_id: integer('shop_id').notNull(),
  product_id: integer('product_id'),
  variant_id: integer('variant_id'),
  title: text('title'),
  quantity: integer('quantity'),
  sku: text('sku'),
  variant_title: text('variant_title'),
  vendor: text('vendor'),
  fulfillment_service: text('fulfillment_service'),
  requires_shipping: integer('requires_shipping', { mode: 'boolean' }),
  taxable: integer('taxable', { mode: 'boolean' }),
  gift_card: integer('gift_card', { mode: 'boolean' }),
  name: text('name'),
  variant_inventory_management: text('variant_inventory_management'),
  properties: text('properties'), // JSON
  product_exists: integer('product_exists', { mode: 'boolean' }),
  fulfillable_quantity: integer('fulfillable_quantity'),
  grams: integer('grams'),
  price: real('price'),
  total_discount: real('total_discount'),
  fulfillment_status: text('fulfillment_status'),
  price_set: text('price_set'), // JSON
  total_discount_set: text('total_discount_set'), // JSON
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const fulfillments = sqliteTable('shopify_fulfillments', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  order_id: integer('order_id').notNull(),
  status: text('status'),
  tracking_company: text('tracking_company'),
  tracking_number: text('tracking_number'),
  tracking_numbers: text('tracking_numbers'), // JSON
  tracking_url: text('tracking_url'),
  tracking_urls: text('tracking_urls'), // JSON
  receipt: text('receipt'), // JSON
  name: text('name'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const plans = sqliteTable('plans', {
  id:            integer('id').primaryKey({ autoIncrement: true }).notNull(),
  name:          text('name').notNull(),
  description:   text('description'),
  monthly_price: real('monthly_price').default(0),
  trial_days:    integer('trial_days').default(0),
  currency:      text('currency').default('CAD'),
  features:      text('features'),               // JSON string → parse in route
  created_at:    text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at:    text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const invoiceSettings = sqliteTable('invoice_settings', {
  id: integer('id').primaryKey({ autoIncrement: true }).notNull(),
  shop_id: integer('shop_id').notNull(),
  brand_name: text('brand_name'),
  business_name: text('business_name'),
  business_address: text('business_address'),
  city: text('city'),
  country: text('country'),
  zip_code: text('zip_code'),
  street: text('street'),
  apartment: text('apartment'),
  state: text('state'),
  additional_info: text('additional_info'),
  phone: text('phone'),
  company_website: text('company_website'),
  support_email: text('support_email'),
  sender_name: text('sender_name').default('Uncap'),
  sender_address: text('sender_address').default('support@uncap.com'),
  logo_url: text('logo_url'),
  logo_url_id: text('logo_url_id'),
  invoice_template: text('invoice_template').default('Design 1'),
  primary_color: text('primary_color').default('#8257d0'),
  secondary_color: text('secondary_color').default('#f0ecf9'),
  primary_text_color: text('primary_text_color').default('#ffffff'),
  invoice_text_color: text('invoice_text_color').default('#000'),
  heading_font: text('heading_font').default('Roboto'),
  body_font: text('body_font').default('Open Sans'),
  paper_size: text('paper_size').default('A4'),
  date_format: text('date_format').default('MM/dd/yyyy'),
  default_due_date: integer('default_due_date').default(0),
  send_invoice: text('send_invoice').default('manuall'),
  auto_invoice_send_condition: text('auto_invoice_send_condition').default('created'),
  new_order_email_title: text('new_order_email_title'),
  new_order_email_content: text('new_order_email_content'),
  edited_order_email_title: text('edited_order_email_title'),
  edited_order_email_content: text('edited_order_email_content'),
  cancelled_order_email_title: text('cancelled_order_email_title'),
  cancelled_order_email_content: text('cancelled_order_email_content'),
  footer_note: text('footer_note'),
  show_image: integer('show_image', { mode: 'boolean' }).default(false),
  show_sku: integer('show_sku', { mode: 'boolean' }).default(false),
  show_barcode: integer('show_barcode', { mode: 'boolean' }).default(false),
  show_weight: integer('show_weight', { mode: 'boolean' }).default(false),
  show_hs_code: integer('show_hs_code', { mode: 'boolean' }).default(false),
  show_country: integer('show_country', { mode: 'boolean' }).default(false),
  show_payment_gateway: integer('show_payment_gateway', { mode: 'boolean' }).default(false),
  show_card_type: integer('show_card_type', { mode: 'boolean' }).default(false),
  show_card_last_digit: integer('show_card_last_digit', { mode: 'boolean' }).default(false),
  show_currency_code: integer('show_currency_code', { mode: 'boolean' }).default(false),
  show_item_total: integer('show_item_total', { mode: 'boolean' }).default(false),
  show_total_quantity: integer('show_total_quantity', { mode: 'boolean' }).default(false),
  show_payment_details: integer('show_payment_details', { mode: 'boolean' }).default(false),
  show_payment_link: integer('show_payment_link', { mode: 'boolean' }).default(false),
  show_order_note: integer('show_order_note', { mode: 'boolean' }).default(false),
  not_show_zero_outstanding: integer('not_show_zero_outstanding', { mode: 'boolean' }).default(true),
  template_settings: text('template_settings'), // JSON
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const invoiceLanguages = sqliteTable('invoice_languages', {
  id: integer('id').primaryKey({ autoIncrement: true }).notNull(),
  shop_id: integer('shop_id').notNull(),
  invoice: text('invoice').default('Invoice'),
  invoice_number: text('invoice_number').default('Invoice#'),
  invoice_date: text('invoice_date').default('INVOICE DATE'),
  bill_to: text('bill_to').default('Bill To'),
  ship_to: text('ship_to').default('Ship To'),
  shipping_address: text('shipping_address').default('Shipping Address'),
  billing_address: text('billing_address').default('Billing Address'),
  phone: text('phone').default('Phone:'),
  payment_info: text('payment_info').default('Make all Checks payable to'),
  item: text('item').default('ITEM'),
  description: text('description').default('Description'),
  qty: text('qty').default('QTY'),
  unit_price: text('unit_price').default('Unit Price'),
  total: text('total').default('Total'),
  subtotal: text('subtotal').default('Subtotal'),
  discount: text('discount').default('Discount'),
  tax: text('tax').default('Tax'),
  shipping: text('shipping').default('Shipping'),
  subtotal_after_discount: text('subtotal_after_discount').default('Subtotal after discount'),
  thank_you_note: text('thank_you_note').default('Thank you for your purchase.'),
  notes: text('notes').default('Notes:'),
  term_condition_title: text('term_condition_title').default('Terms & conditions'),
  term_condition_content: text('term_condition_content'),
  sku: text('sku').default('SKU:'),
  barcode: text('barcode').default('BARCODE:'),
  weight: text('weight').default('Weight:'),
  hs_code: text('hs_code').default('HS Code:'),
  country_of_origin: text('country_of_origin').default('Country Of Origin:'),
  payment_details: text('payment_details').default('Payment Details:'),
  payment_gateway: text('payment_gateway').default('Gateway:'),
  card_type: text('card_type').default('Card:'),
  card_number: text('card_number').default('Card#:'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const schema = { shops, invoices, orders, products, customers, syncs, productVariants, orderLineItems, fulfillments, plans, invoiceSettings, invoiceLanguages };
