import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const shops = sqliteTable('shopify_shops', {
  id: integer('id').primaryKey().notNull(),
  myshopify_domain: text('myshopify_domain').notNull().unique(),
  name: text('name'),
  email: text('email'),
  domain: text('domain'),
  currency: text('currency'),
  timezone: text('timezone'),
  iana_timezone: text('iana_timezone'),
  shop_owner: text('shop_owner'),
  plan_name: text('plan_name'),
  plan_display_name: text('plan_display_name'),
  latitude: real('latitude'),
  longitude: real('longitude'),
  address1: text('address1'),
  address2: text('address2'),
  city: text('city'),
  zip: text('zip'),
  province: text('province'),
  country: text('country'),
  country_code: text('country_code'),
  country_name: text('country_name'),
  phone: text('phone'),
  customer_email: text('customer_email'),
  money_format: text('money_format'),
  money_with_currency_format: text('money_with_currency_format'),
  weight_unit: text('weight_unit'),
  province_code: text('province_code'),
  setup_required: integer('setup_required', { mode: 'boolean' }),
  force_ssl: integer('force_ssl', { mode: 'boolean' }),
  primary_locale: text('primary_locale'),
  primary_location_id: integer('primary_location_id'),
  active_recurring_subscription_id: text('active_recurring_subscription_id'),
  plan_id: integer('plan_id'),
  used_trial_minutes: integer('used_trial_minutes').default(0),
  used_trial_minutes_updated_at: text('used_trial_minutes_updated_at'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  access_token: text('access_token').notNull(),
  scope: text('scope'),
  is_active: integer('is_active', { mode: 'boolean' }).default(true),
  installed_at: text('installed_at').default('CURRENT_TIMESTAMP'),
});

export const invoices = sqliteTable('invoices', {
  id: integer('id').primaryKey({ autoIncrement: true }).notNull(),
  shop_id: integer('shop_id').notNull(),
  order_id: integer('order_id'),
  invoice_number: text('invoice_number').notNull().unique(),
  amount: real('amount'),
  status: text('status').default('draft'),
  due_date: text('due_date'),
  notes: text('notes'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const orders = sqliteTable('shopify_orders', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  customer_id: integer('customer_id'),
  email: text('email'),
  number: integer('number'),
  order_number: integer('order_number'),
  note: text('note'),
  token: text('token'),
  gateway: text('gateway'),
  test: integer('test', { mode: 'boolean' }),
  total_price: real('total_price'),
  subtotal_price: real('subtotal_price'),
  total_weight: integer('total_weight'),
  total_tax: real('total_tax'),
  taxes_included: integer('taxes_included', { mode: 'boolean' }),
  currency: text('currency'),
  financial_status: text('financial_status'),
  confirmed: integer('confirmed', { mode: 'boolean' }),
  total_discounts: real('total_discounts'),
  total_line_items_price: real('total_line_items_price'),
  cart_token: text('cart_token'),
  name: text('name'),
  cancelled_at: text('cancelled_at'),
  cancel_reason: text('cancel_reason'),
  total_price_set: text('total_price_set'),
  subtotal_price_set: text('subtotal_price_set'),
  total_tax_set: text('total_tax_set'),
  total_discounts_set: text('total_discounts_set'),
  total_line_items_price_set: text('total_line_items_price_set'),
  fulfillment_status: text('fulfillment_status'),
  customer_locale: text('customer_locale'),
  processed_at: text('processed_at'),
  status_page_url: text('status_page_url'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  tags: text('tags'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const products = sqliteTable('shopify_products', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  title: text('title').notNull(),
  body_html: text('body_html'),
  vendor: text('vendor'),
  product_type: text('product_type'),
  handle: text('handle'),
  status: text('status'),
  published_at: text('published_at'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const customers = sqliteTable('shopify_customers', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  email: text('email'),
  first_name: text('first_name'),
  last_name: text('last_name'),
  orders_count: integer('orders_count'),
  state: text('state'),
  total_spent: text('total_spent'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const syncs = sqliteTable('shopify_syncs', {
  id: integer('id').primaryKey({ autoIncrement: true }).notNull(),
  shop_id: integer('shop_id'),
  domain: text('domain').notNull(),
  status: text('status'),
  models: text('models'), // JSON string
  error: text('error'),
  created_at: text('created_at').default('CURRENT_TIMESTAMP'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const productVariants = sqliteTable('shopify_product_variants', {
  id: integer('id').primaryKey().notNull(),
  product_id: integer('product_id').notNull(),
  shop_id: integer('shop_id').notNull(),
  title: text('title'),
  price: real('price'),
  sku: text('sku'),
  position: integer('position'),
  inventory_policy: text('inventory_policy'),
  compare_at_price: real('compare_at_price'),
  fulfillment_service: text('fulfillment_service'),
  inventory_management: text('inventory_management'),
  option1: text('option1'),
  option2: text('option2'),
  option3: text('option3'),
  taxable: integer('taxable', { mode: 'boolean' }),
  barcode: text('barcode'),
  grams: integer('grams'),
  inventory_item_id: integer('inventory_item_id'),
  inventory_quantity: integer('inventory_quantity'),
  weight: real('weight'),
  weight_unit: text('weight_unit'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const orderLineItems = sqliteTable('shopify_order_line_items', {
  id: integer('id').primaryKey().notNull(),
  order_id: integer('order_id').notNull(),
  shop_id: integer('shop_id').notNull(),
  product_id: integer('product_id'),
  variant_id: integer('variant_id'),
  title: text('title'),
  quantity: integer('quantity'),
  sku: text('sku'),
  variant_title: text('variant_title'),
  vendor: text('vendor'),
  fulfillment_service: text('fulfillment_service'),
  requires_shipping: integer('requires_shipping', { mode: 'boolean' }),
  taxable: integer('taxable', { mode: 'boolean' }),
  gift_card: integer('gift_card', { mode: 'boolean' }),
  name: text('name'),
  variant_inventory_management: text('variant_inventory_management'),
  properties: text('properties'), // JSON
  product_exists: integer('product_exists', { mode: 'boolean' }),
  fulfillable_quantity: integer('fulfillable_quantity'),
  grams: integer('grams'),
  price: real('price'),
  total_discount: real('total_discount'),
  fulfillment_status: text('fulfillment_status'),
  price_set: text('price_set'), // JSON
  total_discount_set: text('total_discount_set'), // JSON
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const fulfillments = sqliteTable('shopify_fulfillments', {
  id: integer('id').primaryKey().notNull(),
  shop_id: integer('shop_id').notNull(),
  order_id: integer('order_id').notNull(),
  status: text('status'),
  tracking_company: text('tracking_company'),
  tracking_number: text('tracking_number'),
  tracking_numbers: text('tracking_numbers'), // JSON
  tracking_url: text('tracking_url'),
  tracking_urls: text('tracking_urls'), // JSON
  receipt: text('receipt'), // JSON
  name: text('name'),
  shopify_created_at: text('shopify_created_at'),
  shopify_updated_at: text('shopify_updated_at'),
  created_at: text('created_at'),
  updated_at: text('updated_at').default('CURRENT_TIMESTAMP'),
});

export const schema = { shops, invoices, orders, products, customers, syncs, productVariants, orderLineItems, fulfillments };
